# Generated by Django 6.0.6 on 2026-07-14 09:04

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name="Seller")
    Group.objects.get_or_create(name="Admin")
    Group.objects.get_or_create(name="Customer")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
